services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:7860"
    environment:
      - HF_REPO_ID=pedrosall/amazonnet-efficientnet-b3
      - HF_FILENAME=best_efficientnet_finetuned.pthdoc